#!/bin/bash
set -o errexit -o nounset

source "$(which nginx-site)"

USAGE="$0 <site1> {<siteN>}"

if [[ "$#" -lt 1 ]]; then
    echo $USAGE >&2
    exit 1
fi

changed=false
for site in $@; do
    if ! link_path="$(resolve_site "$SITES_ENABLED" "$site")"; then
	echo "Site $site is not present in $SITES_ENABLED." >&2
    else
	rm "$link_path"
	changed=true
    fi
done

if $changed; then
    reload_nginx
fi

