#!/bin/bash
set -o errexit -o errtrace -o nounset

source "$(which nginx-site)"

USAGE="usage: ${PROG:-$0} <site1> {<siteN>}"

if [[ "$#" -lt 1 ]]; then
    echo $USAGE >&2
    exit 1
fi

find_editor

declare -A site_paths
declare -A site_backups

for site in $@; do
    if site_paths[$site]="$(resolve_site "$SITES_AVAILABLE" "$site")"; then
	site_backups[$site]="$(mktemp)"
	cp -f "${site_paths[$site]}" "${site_backups[$site]}"
    else
	site_paths[$site]="$SITES_AVAILABLE/$site$DEFAULT_EXT"
    fi
done

"$EDITOR" "${site_paths[@]}"

changed=false
for site in ${!site_backups[@]}; do
    if ! cmp "${site_paths[$site]}" "${site_backups[$site]}" >&/dev/null; then
	changed=true
    fi
done

if $changed; then
    reload_nginx
else
    echo "No sites were changed, not reloading nginx."
fi

